In [1]:
with open('./data/wizard.txt', 'r', encoding='utf-8') as file:
    text = file.read()

In [2]:
chars = sorted(set(text))

In [3]:
print(chars)

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']


In [4]:
# character Level Tokenizer
###Encodings 
strings_to_int = { ch:i for i , ch in enumerate(chars) }
int_to_string = { i:ch for i, ch in enumerate(chars) }

In [5]:
print("strings to int: ", strings_to_int)
print("int to string: ", int_to_string)

strings to int:  {'\n': 0, ' ': 1, '!': 2, '"': 3, '&': 4, "'": 5, '(': 6, ')': 7, '*': 8, ',': 9, '-': 10, '.': 11, '0': 12, '1': 13, '2': 14, '3': 15, '4': 16, '5': 17, '6': 18, '7': 19, '8': 20, '9': 21, ':': 22, ';': 23, '?': 24, 'A': 25, 'B': 26, 'C': 27, 'D': 28, 'E': 29, 'F': 30, 'G': 31, 'H': 32, 'I': 33, 'J': 34, 'K': 35, 'L': 36, 'M': 37, 'N': 38, 'O': 39, 'P': 40, 'Q': 41, 'R': 42, 'S': 43, 'T': 44, 'U': 45, 'V': 46, 'W': 47, 'X': 48, 'Y': 49, 'Z': 50, '[': 51, ']': 52, '_': 53, 'a': 54, 'b': 55, 'c': 56, 'd': 57, 'e': 58, 'f': 59, 'g': 60, 'h': 61, 'i': 62, 'j': 63, 'k': 64, 'l': 65, 'm': 66, 'n': 67, 'o': 68, 'p': 69, 'q': 70, 'r': 71, 's': 72, 't': 73, 'u': 74, 'v': 75, 'w': 76, 'x': 77, 'y': 78, 'z': 79, '\ufeff': 80}
int to string:  {0: '\n', 1: ' ', 2: '!', 3: '"', 4: '&', 5: "'", 6: '(', 7: ')', 8: '*', 9: ',', 10: '-', 11: '.', 12: '0', 13: '1', 14: '2', 15: '3', 16: '4', 17: '5', 18: '6', 19: '7', 20: '8', 21: '9', 22: ':', 23: ';', 24: '?', 25: 'A', 26: 'B', 27: 'C

In [6]:
encode = lambda s : [strings_to_int[c] for c in s]

In [7]:
decode = lambda l : "".join([int_to_string[i] for i in l])

In [8]:
print(encode("hello"))

[61, 58, 65, 65, 68]


In [9]:
print(decode(encode("hello")))

hello


In [10]:
import torch

In [11]:
torch.__version__

'2.1.1+cpu'

In [12]:
data = torch.tensor(encode(text))

In [13]:
print(data)

tensor([80, 36, 33,  ...,  0,  0,  0])


In [14]:
print(data[:100])

tensor([80, 36, 33, 43, 44,  1, 39, 30,  1, 27, 32, 25, 40, 44, 29, 42, 43,  0,
         0,  0, 27, 32, 25, 40, 44, 29, 42,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 40, 25,
        31, 29,  0,  0,  1,  1, 13,  1, 44, 32])


In [15]:
n = int(0.8 * len(data))
train_data = data[:n]
val_data = data[n:]

In [16]:
round(len(train_data) / len(val_data), 2)

4.0

In [17]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [18]:
print(device)

cpu


In [19]:
probabilities = torch.tensor([0.1, 0.9])

In [20]:
probabilities

tensor([0.1000, 0.9000])

In [21]:
samples = torch.multinomial(probabilities, num_samples = 10, replacement = True)

In [22]:
samples

tensor([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [23]:
tensor_1 = torch.tensor([1, 2, 3, 4, 5])
out = torch.cat((tensor_1, torch.tensor([5])), dim = 0)

In [24]:
out

tensor([1, 2, 3, 4, 5, 5])

In [25]:
out = torch.tril(torch.ones(5, 5))
out # Lower triangles are ones or != 0

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [26]:
out = torch.triu(torch.ones(5,5))
out # Upper Triangles are ones or != 0

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [27]:
torch.stack([torch.tensor([1, 2, 3]), torch.tensor([4, 5, 6]), torch.tensor([7, 8, 9])])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])